angular.module('maxrocky.framework.directives',[
	'maxrocky.framework.directives.rem',
	'maxrocky.framework.directives.title',
    'maxrocky.framework.directives.fullPage',
    'maxrocky.framework.directives.fullPagePic',
    'maxrocky.framework.directives.mrImgConvert',
    'maxrocky.framework.directives.count',
    'maxrocky.framework.directives.fadeInOut'
])